//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCargaEventosCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Registra_actividades_para_enviar_a_CRM
    {
        public int Id_reg { get; set; }
        public Nullable<int> Rut { get; set; }
        public string digito_dv { get; set; }
        public string Tipo_actividad { get; set; }
        public string Nombre_actividad { get; set; }
        public Nullable<int> puntaje { get; set; }
        public Nullable<System.DateTime> Fecha_actividad { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha_proceso_crm { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    }
}
