//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCargaEventosCRM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Fichas20Entities : DbContext
    {
        public Fichas20Entities()
            : base("name=Fichas20Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CRM_Registra_actividades_para_enviar_a_CRM> CRM_Registra_actividades_para_enviar_a_CRM { get; set; }
    
        public virtual ObjectResult<CRM_envia_datos_clientePotencial_Result> CRM_envia_datos_clientePotencial(Nullable<int> rut)
        {
            var rutParameter = rut.HasValue ?
                new ObjectParameter("rut", rut) :
                new ObjectParameter("rut", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRM_envia_datos_clientePotencial_Result>("CRM_envia_datos_clientePotencial", rutParameter);
        }
    
        public virtual int CRM_RegistroUpdate(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CRM_RegistroUpdate", idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> CRM_Eventos_Insert(string xml_IN, string method, string response, string origen)
        {
            var xml_INParameter = xml_IN != null ?
                new ObjectParameter("Xml_IN", xml_IN) :
                new ObjectParameter("Xml_IN", typeof(string));
    
            var methodParameter = method != null ?
                new ObjectParameter("Method", method) :
                new ObjectParameter("Method", typeof(string));
    
            var responseParameter = response != null ?
                new ObjectParameter("Response", response) :
                new ObjectParameter("Response", typeof(string));
    
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("CRM_Eventos_Insert", xml_INParameter, methodParameter, responseParameter, origenParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CRM_Eventos_Cerrar(Nullable<int> iD, string response)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var responseParameter = response != null ?
                new ObjectParameter("Response", response) :
                new ObjectParameter("Response", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CRM_Eventos_Cerrar", iDParameter, responseParameter);
        }
    }
}
